name: Publish Git History Analyzer Python Package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.13, 3.11.7, 3.12.3]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install setuptools
        run: pip install setuptools

      - name: Install wheel
        run: pip install wheel

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Zip build directory
        run: zip -r build.zip build/  # Create the zip file

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-package  # Artifact name
          path: build.zip  # Path to the zip file to upload

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v3
        with:
          name: python-package  # Artifact name to download

      - name: List files in the working directory
        run: ls -al

      - name: Unzip package
        run: unzip python-package.zip  # Unzip the downloaded zip file

      - name: List files after unzip artifact
        run: ls -al

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: ./build  # Ensure this points to the correct unpacked package directory
